### PR TITLE
Load CSS files asynchronously

### PR DESCRIPTION
**Pull request by bramstein**
*Needs review.*

Thanks to the filamentgroup for https://github.com/filamentgroup/loadCSS and Paul Irish for bringing this up.

cc @paulirish @scottjehl @zachleat

### CODE REVIEW

**Comment by scottjehl** [comment]
Looks solid, @bramstein! Really glad to see this rolled into Typekit. :)

**Comment by mephraim** [comment]
:+1:

**Comment by zachleat** [comment]
:+1:

**Comment by kennethormandy** [comment]
This is an awesome addition, thanks everyone!

**Comment by paulirish** [comment]
@bramstein  I just saw the followup commit over here https://github.com/typekit/webfontloader/commit/2e58c0cbb5d5e4b9616970842c8ef44c6cb289d6

Under what circumstances with the opt-in async behavior trigger?

**Comment by bramstein** [comment]
@paulirish I did some testing with these changes and while it improved performance it also broke the default behaviour many of our customers expect: Typekit blocks rendering (as bad as it is). Therefor I decided to turn this into an opt-in feature that can be enabled by passing a new configuration option to the Typekit loader.

Anyone wishing to try it out can set the `async` option to `true` when they call `Typekit.load`:

```
Typekit.load({ async: true });
```

The `async` parameter is going to be turned on by default for new kits.

The code for this is already in production, but I haven't had time to write a blog post about it. The blog post will introduce this new option and encourage all of our customers to switch to the asynchronous embed code (so the Typekit JS loads asynchronously) and use `async` (so the CSS isn't blocking either).

**Comment by bramstein** [comment]
@paulirish As for the other modules, I would prefer those to load CSS asynchronously as well, but I'm hesitant to make changes without the approval of the module owners (e.g. Google, Fontdeck, Monotype).

**Comment by scottjehl** [comment]
So great to hear that async will be the default for new kits, @bramstein !

**Pull request merged**
