### PR TITLE
Use appended min to highlight minified state

### PR DESCRIPTION
**Pull request by KLVTZ**
`webfont.js` in root is a minified file. 

We should reflect this in the name. This would also make globbing easier.

### CODE REVIEW

**Comment by KLVTZ** [comment]
Changed all `webfontloader.js` to `webfontloader.min.js`. I wasn't sure if that was okay or we isolate this minified version to a sub-folder? Since the minified version already lives in root, I figured we could keep it there.

**Comment by bramstein** [comment]
@KLVTZ This is a good idea, but I think there are projects depending on webfontloader.js being available in the root. Due to the Closure Compiler we can't generate a non-compressed file. Including the same file twice seems suboptimal, so I prefer it if we keep the current convention (unless you have another suggestion).

**Comment by KLVTZ** [comment]
@bramstein this is the first project that I have encountered that uses the Closure Compiler. Is the option to generate a non-compressed file just not available or does it go against the best optimization it can provide?

**Comment by bramstein** [comment]
@KLVTZ It is possible to generate what basically amounts to a concatenated collection of files, but due to the nature of the code, it'll export a lot of global variables and functions (which should remain internal). Minifying it without closure compiler is unlikely to produce good results.

Closure compiler has a "debug" mode, but it doesn't generate easily readable output.

**Comment by KLVTZ** [comment]
@bramstein thanks for explaining! Looks like there isn't an ideal solution for this at the moment. Maybe later we can revisit? I'll leave the option to close this be up to you.

**Comment by bramstein** [comment]
No problem. I think for now it is best to maintain the current setup. I'll close this issue, but thanks for bringing it up.

**Pull request closed without merging**
